### PR TITLE
Adding properties field to customers schema

### PR DESCRIPTION
**Pull request by arthur-borcato**
# Description of change
Adding properties field on customers schema, so we should be able to fetch custom properties created by the users on the customers endpoint

# Manual QA steps
- Create a custom property for customers
- Fetch customers data
- You should be able to see the created custom property on "properties" field
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by arthur-borcato** [comment]
@kspeer825 - when you have some time, could you please take a look here? It's something really important on the project that I'm working, we need this data to generate some reports.

**Comment by kethan1122** [comment]
@arthur-borcato we are reviewing this PR along with other changes. We are planning to release these changes by first week of February.

**Review by kethan1122 — APPROVED** [review]

**Comment by kethan1122** [comment]
@arthur-borcato I would need your permission to merge your branch to our feature branch (TDL-21651-code-refactoring) where all other changes will be coming to and I would create a new PR to merge (TDL-21651-code-refactoring) to master and release the changes.
Thanks

**Review by kethan1122 — DISMISSED** [review]

**Comment by arthur-borcato** [comment]
Hi @kethan1122. Sure, thank you so much for that.

**Comment by kethan1122** [comment]
Thanks @arthur-borcato for confirming, I'm going to merge this. I will let you know once release is done.
Thanks

**Comment by kethan1122** [comment]
Hello @arthur-borcato. This PR for adding custom_field `properties` of `customers` stream has been merged to master and released as part of Version `1.1.1`

**Comment by arthur-borcato** [comment]
> Hello @arthur-borcato. This PR for adding custom_field `properties` of `customers` stream has been merged to master and released as part of Version `1.1.1`

Thank you so much, @kethan1122. I'm using it right now and it's working as expected. Thanks!

**Pull request merged**
